apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-task1
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3 
    ssh:
      publicKeyName: key1
  